// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.unicamp.mc536.t2010s2a.forum.domain;

import br.unicamp.mc536.t2010s2a.forum.domain.DocumentoDataOnDemand;
import br.unicamp.mc536.t2010s2a.forum.domain.DocumentoVinculo;
import br.unicamp.mc536.t2010s2a.forum.domain.UsuarioDataOnDemand;
import java.util.List;
import java.util.Random;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DocumentoVinculoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: DocumentoVinculoDataOnDemand: @Component;
    
    private Random DocumentoVinculoDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<DocumentoVinculo> DocumentoVinculoDataOnDemand.data;
    
    @Autowired
    private DocumentoDataOnDemand DocumentoVinculoDataOnDemand.documentoDataOnDemand;
    
    @Autowired
    private UsuarioDataOnDemand DocumentoVinculoDataOnDemand.usuarioDataOnDemand;
    
    public DocumentoVinculo DocumentoVinculoDataOnDemand.getNewTransientDocumentoVinculo(int index) {
        br.unicamp.mc536.t2010s2a.forum.domain.DocumentoVinculo obj = new br.unicamp.mc536.t2010s2a.forum.domain.DocumentoVinculo();
        obj.setDsVinculo("dsVinculo_" + index);
        obj.setDtInclusao(new java.util.Date());
        obj.setIdDocumento(documentoDataOnDemand.getRandomDocumento());
        obj.setIdUsuario(usuarioDataOnDemand.getRandomUsuario());
        obj.setTpReferenciaDocumento(br.unicamp.mc536.t2010s2a.forum.reference.ReferenciaDocumento.class.getEnumConstants()[0]);
        return obj;
    }
    
    public DocumentoVinculo DocumentoVinculoDataOnDemand.getSpecificDocumentoVinculo(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        DocumentoVinculo obj = data.get(index);
        return DocumentoVinculo.findDocumentoVinculo(obj.getId());
    }
    
    public DocumentoVinculo DocumentoVinculoDataOnDemand.getRandomDocumentoVinculo() {
        init();
        DocumentoVinculo obj = data.get(rnd.nextInt(data.size()));
        return DocumentoVinculo.findDocumentoVinculo(obj.getId());
    }
    
    public boolean DocumentoVinculoDataOnDemand.modifyDocumentoVinculo(DocumentoVinculo obj) {
        return false;
    }
    
    @Transactional(propagation = Propagation.REQUIRES_NEW)
    public void DocumentoVinculoDataOnDemand.init() {
        if (data != null && !data.isEmpty()) {
            return;
        }
        
        data = br.unicamp.mc536.t2010s2a.forum.domain.DocumentoVinculo.findDocumentoVinculoEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'DocumentoVinculo' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<br.unicamp.mc536.t2010s2a.forum.domain.DocumentoVinculo>();
        for (int i = 0; i < 10; i++) {
            br.unicamp.mc536.t2010s2a.forum.domain.DocumentoVinculo obj = getNewTransientDocumentoVinculo(i);
            obj.persist();
            data.add(obj);
        }
    }
    
}
