// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.unicamp.mc536.t2010s2a.forum.domain;

import br.unicamp.mc536.t2010s2a.forum.domain.DocumentoDataOnDemand;
import br.unicamp.mc536.t2010s2a.forum.domain.DocumentoReferenciaPais;
import br.unicamp.mc536.t2010s2a.forum.domain.PaisDataOnDemand;
import java.util.List;
import java.util.Random;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DocumentoReferenciaPaisDataOnDemand_Roo_DataOnDemand {
    
    declare @type: DocumentoReferenciaPaisDataOnDemand: @Component;
    
    private Random DocumentoReferenciaPaisDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<DocumentoReferenciaPais> DocumentoReferenciaPaisDataOnDemand.data;
    
    @Autowired
    private DocumentoDataOnDemand DocumentoReferenciaPaisDataOnDemand.documentoDataOnDemand;
    
    @Autowired
    private PaisDataOnDemand DocumentoReferenciaPaisDataOnDemand.paisDataOnDemand;
    
    public DocumentoReferenciaPais DocumentoReferenciaPaisDataOnDemand.getNewTransientDocumentoReferenciaPais(int index) {
        br.unicamp.mc536.t2010s2a.forum.domain.DocumentoReferenciaPais obj = new br.unicamp.mc536.t2010s2a.forum.domain.DocumentoReferenciaPais();
        obj.setIdDocumento(documentoDataOnDemand.getRandomDocumento());
        obj.setIdPais(paisDataOnDemand.getRandomPais());
        return obj;
    }
    
    public DocumentoReferenciaPais DocumentoReferenciaPaisDataOnDemand.getSpecificDocumentoReferenciaPais(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        DocumentoReferenciaPais obj = data.get(index);
        return DocumentoReferenciaPais.findDocumentoReferenciaPais(obj.getId());
    }
    
    public DocumentoReferenciaPais DocumentoReferenciaPaisDataOnDemand.getRandomDocumentoReferenciaPais() {
        init();
        DocumentoReferenciaPais obj = data.get(rnd.nextInt(data.size()));
        return DocumentoReferenciaPais.findDocumentoReferenciaPais(obj.getId());
    }
    
    public boolean DocumentoReferenciaPaisDataOnDemand.modifyDocumentoReferenciaPais(DocumentoReferenciaPais obj) {
        return false;
    }
    
    @Transactional(propagation = Propagation.REQUIRES_NEW)
    public void DocumentoReferenciaPaisDataOnDemand.init() {
        if (data != null && !data.isEmpty()) {
            return;
        }
        
        data = br.unicamp.mc536.t2010s2a.forum.domain.DocumentoReferenciaPais.findDocumentoReferenciaPaisEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'DocumentoReferenciaPais' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<br.unicamp.mc536.t2010s2a.forum.domain.DocumentoReferenciaPais>();
        for (int i = 0; i < 10; i++) {
            br.unicamp.mc536.t2010s2a.forum.domain.DocumentoReferenciaPais obj = getNewTransientDocumentoReferenciaPais(i);
            obj.persist();
            data.add(obj);
        }
    }
    
}
