// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.unicamp.mc536.t2010s2a.forum.domain;

import br.unicamp.mc536.t2010s2a.forum.domain.DocumentoReferenciaPaisDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DocumentoReferenciaPaisIntegrationTest_Roo_IntegrationTest {
    
    declare @type: DocumentoReferenciaPaisIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: DocumentoReferenciaPaisIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    @Autowired
    private DocumentoReferenciaPaisDataOnDemand DocumentoReferenciaPaisIntegrationTest.dod;
    
    @Test
    public void DocumentoReferenciaPaisIntegrationTest.testCountDocumentoReferenciaPaises() {
        org.junit.Assert.assertNotNull("Data on demand for 'DocumentoReferenciaPais' failed to initialize correctly", dod.getRandomDocumentoReferenciaPais());
        long count = br.unicamp.mc536.t2010s2a.forum.domain.DocumentoReferenciaPais.countDocumentoReferenciaPaises();
        org.junit.Assert.assertTrue("Counter for 'DocumentoReferenciaPais' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void DocumentoReferenciaPaisIntegrationTest.testFindDocumentoReferenciaPais() {
        br.unicamp.mc536.t2010s2a.forum.domain.DocumentoReferenciaPais obj = dod.getRandomDocumentoReferenciaPais();
        org.junit.Assert.assertNotNull("Data on demand for 'DocumentoReferenciaPais' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'DocumentoReferenciaPais' failed to provide an identifier", id);
        obj = br.unicamp.mc536.t2010s2a.forum.domain.DocumentoReferenciaPais.findDocumentoReferenciaPais(id);
        org.junit.Assert.assertNotNull("Find method for 'DocumentoReferenciaPais' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'DocumentoReferenciaPais' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void DocumentoReferenciaPaisIntegrationTest.testFindAllDocumentoReferenciaPaises() {
        org.junit.Assert.assertNotNull("Data on demand for 'DocumentoReferenciaPais' failed to initialize correctly", dod.getRandomDocumentoReferenciaPais());
        long count = br.unicamp.mc536.t2010s2a.forum.domain.DocumentoReferenciaPais.countDocumentoReferenciaPaises();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'DocumentoReferenciaPais', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<br.unicamp.mc536.t2010s2a.forum.domain.DocumentoReferenciaPais> result = br.unicamp.mc536.t2010s2a.forum.domain.DocumentoReferenciaPais.findAllDocumentoReferenciaPaises();
        org.junit.Assert.assertNotNull("Find all method for 'DocumentoReferenciaPais' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'DocumentoReferenciaPais' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void DocumentoReferenciaPaisIntegrationTest.testFindDocumentoReferenciaPaisEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'DocumentoReferenciaPais' failed to initialize correctly", dod.getRandomDocumentoReferenciaPais());
        long count = br.unicamp.mc536.t2010s2a.forum.domain.DocumentoReferenciaPais.countDocumentoReferenciaPaises();
        if (count > 20) count = 20;
        java.util.List<br.unicamp.mc536.t2010s2a.forum.domain.DocumentoReferenciaPais> result = br.unicamp.mc536.t2010s2a.forum.domain.DocumentoReferenciaPais.findDocumentoReferenciaPaisEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'DocumentoReferenciaPais' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'DocumentoReferenciaPais' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    @Transactional
    public void DocumentoReferenciaPaisIntegrationTest.testFlush() {
        br.unicamp.mc536.t2010s2a.forum.domain.DocumentoReferenciaPais obj = dod.getRandomDocumentoReferenciaPais();
        org.junit.Assert.assertNotNull("Data on demand for 'DocumentoReferenciaPais' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'DocumentoReferenciaPais' failed to provide an identifier", id);
        obj = br.unicamp.mc536.t2010s2a.forum.domain.DocumentoReferenciaPais.findDocumentoReferenciaPais(id);
        org.junit.Assert.assertNotNull("Find method for 'DocumentoReferenciaPais' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyDocumentoReferenciaPais(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'DocumentoReferenciaPais' failed to increment on flush directive", obj.getVersion() > currentVersion || !modified);
    }
    
    @Test
    @Transactional
    public void DocumentoReferenciaPaisIntegrationTest.testMerge() {
        br.unicamp.mc536.t2010s2a.forum.domain.DocumentoReferenciaPais obj = dod.getRandomDocumentoReferenciaPais();
        org.junit.Assert.assertNotNull("Data on demand for 'DocumentoReferenciaPais' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'DocumentoReferenciaPais' failed to provide an identifier", id);
        obj = br.unicamp.mc536.t2010s2a.forum.domain.DocumentoReferenciaPais.findDocumentoReferenciaPais(id);
        boolean modified =  dod.modifyDocumentoReferenciaPais(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.merge();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'DocumentoReferenciaPais' failed to increment on merge and flush directive", obj.getVersion() > currentVersion || !modified);
    }
    
    @Test
    @Transactional
    public void DocumentoReferenciaPaisIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'DocumentoReferenciaPais' failed to initialize correctly", dod.getRandomDocumentoReferenciaPais());
        br.unicamp.mc536.t2010s2a.forum.domain.DocumentoReferenciaPais obj = dod.getNewTransientDocumentoReferenciaPais(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'DocumentoReferenciaPais' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'DocumentoReferenciaPais' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'DocumentoReferenciaPais' identifier to no longer be null", obj.getId());
    }
    
    @Test
    @Transactional
    public void DocumentoReferenciaPaisIntegrationTest.testRemove() {
        br.unicamp.mc536.t2010s2a.forum.domain.DocumentoReferenciaPais obj = dod.getRandomDocumentoReferenciaPais();
        org.junit.Assert.assertNotNull("Data on demand for 'DocumentoReferenciaPais' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'DocumentoReferenciaPais' failed to provide an identifier", id);
        obj = br.unicamp.mc536.t2010s2a.forum.domain.DocumentoReferenciaPais.findDocumentoReferenciaPais(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'DocumentoReferenciaPais' with identifier '" + id + "'", br.unicamp.mc536.t2010s2a.forum.domain.DocumentoReferenciaPais.findDocumentoReferenciaPais(id));
    }
    
}
