// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.unicamp.mc536.t2010s2a.forum.domain;

import br.unicamp.mc536.t2010s2a.forum.domain.ProgramaUsuarioDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ProgramaUsuarioIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ProgramaUsuarioIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ProgramaUsuarioIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    @Autowired
    private ProgramaUsuarioDataOnDemand ProgramaUsuarioIntegrationTest.dod;
    
    @Test
    public void ProgramaUsuarioIntegrationTest.testCountProgramaUsuarios() {
        org.junit.Assert.assertNotNull("Data on demand for 'ProgramaUsuario' failed to initialize correctly", dod.getRandomProgramaUsuario());
        long count = br.unicamp.mc536.t2010s2a.forum.domain.ProgramaUsuario.countProgramaUsuarios();
        org.junit.Assert.assertTrue("Counter for 'ProgramaUsuario' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ProgramaUsuarioIntegrationTest.testFindProgramaUsuario() {
        br.unicamp.mc536.t2010s2a.forum.domain.ProgramaUsuario obj = dod.getRandomProgramaUsuario();
        org.junit.Assert.assertNotNull("Data on demand for 'ProgramaUsuario' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ProgramaUsuario' failed to provide an identifier", id);
        obj = br.unicamp.mc536.t2010s2a.forum.domain.ProgramaUsuario.findProgramaUsuario(id);
        org.junit.Assert.assertNotNull("Find method for 'ProgramaUsuario' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'ProgramaUsuario' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ProgramaUsuarioIntegrationTest.testFindAllProgramaUsuarios() {
        org.junit.Assert.assertNotNull("Data on demand for 'ProgramaUsuario' failed to initialize correctly", dod.getRandomProgramaUsuario());
        long count = br.unicamp.mc536.t2010s2a.forum.domain.ProgramaUsuario.countProgramaUsuarios();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'ProgramaUsuario', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<br.unicamp.mc536.t2010s2a.forum.domain.ProgramaUsuario> result = br.unicamp.mc536.t2010s2a.forum.domain.ProgramaUsuario.findAllProgramaUsuarios();
        org.junit.Assert.assertNotNull("Find all method for 'ProgramaUsuario' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'ProgramaUsuario' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ProgramaUsuarioIntegrationTest.testFindProgramaUsuarioEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'ProgramaUsuario' failed to initialize correctly", dod.getRandomProgramaUsuario());
        long count = br.unicamp.mc536.t2010s2a.forum.domain.ProgramaUsuario.countProgramaUsuarios();
        if (count > 20) count = 20;
        java.util.List<br.unicamp.mc536.t2010s2a.forum.domain.ProgramaUsuario> result = br.unicamp.mc536.t2010s2a.forum.domain.ProgramaUsuario.findProgramaUsuarioEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'ProgramaUsuario' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'ProgramaUsuario' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    @Transactional
    public void ProgramaUsuarioIntegrationTest.testFlush() {
        br.unicamp.mc536.t2010s2a.forum.domain.ProgramaUsuario obj = dod.getRandomProgramaUsuario();
        org.junit.Assert.assertNotNull("Data on demand for 'ProgramaUsuario' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ProgramaUsuario' failed to provide an identifier", id);
        obj = br.unicamp.mc536.t2010s2a.forum.domain.ProgramaUsuario.findProgramaUsuario(id);
        org.junit.Assert.assertNotNull("Find method for 'ProgramaUsuario' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyProgramaUsuario(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'ProgramaUsuario' failed to increment on flush directive", obj.getVersion() > currentVersion || !modified);
    }
    
    @Test
    @Transactional
    public void ProgramaUsuarioIntegrationTest.testMerge() {
        br.unicamp.mc536.t2010s2a.forum.domain.ProgramaUsuario obj = dod.getRandomProgramaUsuario();
        org.junit.Assert.assertNotNull("Data on demand for 'ProgramaUsuario' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ProgramaUsuario' failed to provide an identifier", id);
        obj = br.unicamp.mc536.t2010s2a.forum.domain.ProgramaUsuario.findProgramaUsuario(id);
        boolean modified =  dod.modifyProgramaUsuario(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.merge();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'ProgramaUsuario' failed to increment on merge and flush directive", obj.getVersion() > currentVersion || !modified);
    }
    
    @Test
    @Transactional
    public void ProgramaUsuarioIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'ProgramaUsuario' failed to initialize correctly", dod.getRandomProgramaUsuario());
        br.unicamp.mc536.t2010s2a.forum.domain.ProgramaUsuario obj = dod.getNewTransientProgramaUsuario(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'ProgramaUsuario' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'ProgramaUsuario' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'ProgramaUsuario' identifier to no longer be null", obj.getId());
    }
    
    @Test
    @Transactional
    public void ProgramaUsuarioIntegrationTest.testRemove() {
        br.unicamp.mc536.t2010s2a.forum.domain.ProgramaUsuario obj = dod.getRandomProgramaUsuario();
        org.junit.Assert.assertNotNull("Data on demand for 'ProgramaUsuario' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ProgramaUsuario' failed to provide an identifier", id);
        obj = br.unicamp.mc536.t2010s2a.forum.domain.ProgramaUsuario.findProgramaUsuario(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'ProgramaUsuario' with identifier '" + id + "'", br.unicamp.mc536.t2010s2a.forum.domain.ProgramaUsuario.findProgramaUsuario(id));
    }
    
}
