// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.unicamp.mc536.t2010s2a.forum.domain;

import br.unicamp.mc536.t2010s2a.forum.domain.ProgramaDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ProgramaIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ProgramaIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ProgramaIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    @Autowired
    private ProgramaDataOnDemand ProgramaIntegrationTest.dod;
    
    @Test
    public void ProgramaIntegrationTest.testCountProgramas() {
        org.junit.Assert.assertNotNull("Data on demand for 'Programa' failed to initialize correctly", dod.getRandomPrograma());
        long count = br.unicamp.mc536.t2010s2a.forum.domain.Programa.countProgramas();
        org.junit.Assert.assertTrue("Counter for 'Programa' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ProgramaIntegrationTest.testFindPrograma() {
        br.unicamp.mc536.t2010s2a.forum.domain.Programa obj = dod.getRandomPrograma();
        org.junit.Assert.assertNotNull("Data on demand for 'Programa' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Programa' failed to provide an identifier", id);
        obj = br.unicamp.mc536.t2010s2a.forum.domain.Programa.findPrograma(id);
        org.junit.Assert.assertNotNull("Find method for 'Programa' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Programa' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ProgramaIntegrationTest.testFindAllProgramas() {
        org.junit.Assert.assertNotNull("Data on demand for 'Programa' failed to initialize correctly", dod.getRandomPrograma());
        long count = br.unicamp.mc536.t2010s2a.forum.domain.Programa.countProgramas();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Programa', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<br.unicamp.mc536.t2010s2a.forum.domain.Programa> result = br.unicamp.mc536.t2010s2a.forum.domain.Programa.findAllProgramas();
        org.junit.Assert.assertNotNull("Find all method for 'Programa' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Programa' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ProgramaIntegrationTest.testFindProgramaEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Programa' failed to initialize correctly", dod.getRandomPrograma());
        long count = br.unicamp.mc536.t2010s2a.forum.domain.Programa.countProgramas();
        if (count > 20) count = 20;
        java.util.List<br.unicamp.mc536.t2010s2a.forum.domain.Programa> result = br.unicamp.mc536.t2010s2a.forum.domain.Programa.findProgramaEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Programa' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Programa' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    @Transactional
    public void ProgramaIntegrationTest.testFlush() {
        br.unicamp.mc536.t2010s2a.forum.domain.Programa obj = dod.getRandomPrograma();
        org.junit.Assert.assertNotNull("Data on demand for 'Programa' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Programa' failed to provide an identifier", id);
        obj = br.unicamp.mc536.t2010s2a.forum.domain.Programa.findPrograma(id);
        org.junit.Assert.assertNotNull("Find method for 'Programa' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPrograma(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Programa' failed to increment on flush directive", obj.getVersion() > currentVersion || !modified);
    }
    
    @Test
    @Transactional
    public void ProgramaIntegrationTest.testMerge() {
        br.unicamp.mc536.t2010s2a.forum.domain.Programa obj = dod.getRandomPrograma();
        org.junit.Assert.assertNotNull("Data on demand for 'Programa' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Programa' failed to provide an identifier", id);
        obj = br.unicamp.mc536.t2010s2a.forum.domain.Programa.findPrograma(id);
        boolean modified =  dod.modifyPrograma(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.merge();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Programa' failed to increment on merge and flush directive", obj.getVersion() > currentVersion || !modified);
    }
    
    @Test
    @Transactional
    public void ProgramaIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Programa' failed to initialize correctly", dod.getRandomPrograma());
        br.unicamp.mc536.t2010s2a.forum.domain.Programa obj = dod.getNewTransientPrograma(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Programa' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Programa' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Programa' identifier to no longer be null", obj.getId());
    }
    
    @Test
    @Transactional
    public void ProgramaIntegrationTest.testRemove() {
        br.unicamp.mc536.t2010s2a.forum.domain.Programa obj = dod.getRandomPrograma();
        org.junit.Assert.assertNotNull("Data on demand for 'Programa' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Programa' failed to provide an identifier", id);
        obj = br.unicamp.mc536.t2010s2a.forum.domain.Programa.findPrograma(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Programa' with identifier '" + id + "'", br.unicamp.mc536.t2010s2a.forum.domain.Programa.findPrograma(id));
    }
    
}
