// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.unicamp.mc536.t2010s2a.forum.domain;

import br.unicamp.mc536.t2010s2a.forum.domain.RedeTrabalhoDataOnDemand;
import br.unicamp.mc536.t2010s2a.forum.domain.RedeTrabalhoUsuario;
import br.unicamp.mc536.t2010s2a.forum.domain.UsuarioDataOnDemand;
import java.util.List;
import java.util.Random;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

privileged aspect RedeTrabalhoUsuarioDataOnDemand_Roo_DataOnDemand {
    
    declare @type: RedeTrabalhoUsuarioDataOnDemand: @Component;
    
    private Random RedeTrabalhoUsuarioDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<RedeTrabalhoUsuario> RedeTrabalhoUsuarioDataOnDemand.data;
    
    @Autowired
    private RedeTrabalhoDataOnDemand RedeTrabalhoUsuarioDataOnDemand.redeTrabalhoDataOnDemand;
    
    @Autowired
    private UsuarioDataOnDemand RedeTrabalhoUsuarioDataOnDemand.usuarioDataOnDemand;
    
    public RedeTrabalhoUsuario RedeTrabalhoUsuarioDataOnDemand.getNewTransientRedeTrabalhoUsuario(int index) {
        br.unicamp.mc536.t2010s2a.forum.domain.RedeTrabalhoUsuario obj = new br.unicamp.mc536.t2010s2a.forum.domain.RedeTrabalhoUsuario();
        obj.setIdRedeTrabalho(redeTrabalhoDataOnDemand.getRandomRedeTrabalho());
        obj.setIdUsuario(usuarioDataOnDemand.getRandomUsuario());
        return obj;
    }
    
    public RedeTrabalhoUsuario RedeTrabalhoUsuarioDataOnDemand.getSpecificRedeTrabalhoUsuario(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        RedeTrabalhoUsuario obj = data.get(index);
        return RedeTrabalhoUsuario.findRedeTrabalhoUsuario(obj.getId());
    }
    
    public RedeTrabalhoUsuario RedeTrabalhoUsuarioDataOnDemand.getRandomRedeTrabalhoUsuario() {
        init();
        RedeTrabalhoUsuario obj = data.get(rnd.nextInt(data.size()));
        return RedeTrabalhoUsuario.findRedeTrabalhoUsuario(obj.getId());
    }
    
    public boolean RedeTrabalhoUsuarioDataOnDemand.modifyRedeTrabalhoUsuario(RedeTrabalhoUsuario obj) {
        return false;
    }
    
    @Transactional(propagation = Propagation.REQUIRES_NEW)
    public void RedeTrabalhoUsuarioDataOnDemand.init() {
        if (data != null && !data.isEmpty()) {
            return;
        }
        
        data = br.unicamp.mc536.t2010s2a.forum.domain.RedeTrabalhoUsuario.findRedeTrabalhoUsuarioEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'RedeTrabalhoUsuario' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<br.unicamp.mc536.t2010s2a.forum.domain.RedeTrabalhoUsuario>();
        for (int i = 0; i < 10; i++) {
            br.unicamp.mc536.t2010s2a.forum.domain.RedeTrabalhoUsuario obj = getNewTransientRedeTrabalhoUsuario(i);
            obj.persist();
            data.add(obj);
        }
    }
    
}
