// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.unicamp.mc536.t2010s2a.forum.domain;

import br.unicamp.mc536.t2010s2a.forum.domain.RedeTrabalhoDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect RedeTrabalhoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: RedeTrabalhoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: RedeTrabalhoIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    @Autowired
    private RedeTrabalhoDataOnDemand RedeTrabalhoIntegrationTest.dod;
    
    @Test
    public void RedeTrabalhoIntegrationTest.testCountRedeTrabalhoes() {
        org.junit.Assert.assertNotNull("Data on demand for 'RedeTrabalho' failed to initialize correctly", dod.getRandomRedeTrabalho());
        long count = br.unicamp.mc536.t2010s2a.forum.domain.RedeTrabalho.countRedeTrabalhoes();
        org.junit.Assert.assertTrue("Counter for 'RedeTrabalho' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void RedeTrabalhoIntegrationTest.testFindRedeTrabalho() {
        br.unicamp.mc536.t2010s2a.forum.domain.RedeTrabalho obj = dod.getRandomRedeTrabalho();
        org.junit.Assert.assertNotNull("Data on demand for 'RedeTrabalho' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'RedeTrabalho' failed to provide an identifier", id);
        obj = br.unicamp.mc536.t2010s2a.forum.domain.RedeTrabalho.findRedeTrabalho(id);
        org.junit.Assert.assertNotNull("Find method for 'RedeTrabalho' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'RedeTrabalho' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void RedeTrabalhoIntegrationTest.testFindAllRedeTrabalhoes() {
        org.junit.Assert.assertNotNull("Data on demand for 'RedeTrabalho' failed to initialize correctly", dod.getRandomRedeTrabalho());
        long count = br.unicamp.mc536.t2010s2a.forum.domain.RedeTrabalho.countRedeTrabalhoes();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'RedeTrabalho', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<br.unicamp.mc536.t2010s2a.forum.domain.RedeTrabalho> result = br.unicamp.mc536.t2010s2a.forum.domain.RedeTrabalho.findAllRedeTrabalhoes();
        org.junit.Assert.assertNotNull("Find all method for 'RedeTrabalho' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'RedeTrabalho' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void RedeTrabalhoIntegrationTest.testFindRedeTrabalhoEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'RedeTrabalho' failed to initialize correctly", dod.getRandomRedeTrabalho());
        long count = br.unicamp.mc536.t2010s2a.forum.domain.RedeTrabalho.countRedeTrabalhoes();
        if (count > 20) count = 20;
        java.util.List<br.unicamp.mc536.t2010s2a.forum.domain.RedeTrabalho> result = br.unicamp.mc536.t2010s2a.forum.domain.RedeTrabalho.findRedeTrabalhoEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'RedeTrabalho' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'RedeTrabalho' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    @Transactional
    public void RedeTrabalhoIntegrationTest.testFlush() {
        br.unicamp.mc536.t2010s2a.forum.domain.RedeTrabalho obj = dod.getRandomRedeTrabalho();
        org.junit.Assert.assertNotNull("Data on demand for 'RedeTrabalho' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'RedeTrabalho' failed to provide an identifier", id);
        obj = br.unicamp.mc536.t2010s2a.forum.domain.RedeTrabalho.findRedeTrabalho(id);
        org.junit.Assert.assertNotNull("Find method for 'RedeTrabalho' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyRedeTrabalho(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'RedeTrabalho' failed to increment on flush directive", obj.getVersion() > currentVersion || !modified);
    }
    
    @Test
    @Transactional
    public void RedeTrabalhoIntegrationTest.testMerge() {
        br.unicamp.mc536.t2010s2a.forum.domain.RedeTrabalho obj = dod.getRandomRedeTrabalho();
        org.junit.Assert.assertNotNull("Data on demand for 'RedeTrabalho' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'RedeTrabalho' failed to provide an identifier", id);
        obj = br.unicamp.mc536.t2010s2a.forum.domain.RedeTrabalho.findRedeTrabalho(id);
        boolean modified =  dod.modifyRedeTrabalho(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.merge();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'RedeTrabalho' failed to increment on merge and flush directive", obj.getVersion() > currentVersion || !modified);
    }
    
    @Test
    @Transactional
    public void RedeTrabalhoIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'RedeTrabalho' failed to initialize correctly", dod.getRandomRedeTrabalho());
        br.unicamp.mc536.t2010s2a.forum.domain.RedeTrabalho obj = dod.getNewTransientRedeTrabalho(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'RedeTrabalho' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'RedeTrabalho' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'RedeTrabalho' identifier to no longer be null", obj.getId());
    }
    
    @Test
    @Transactional
    public void RedeTrabalhoIntegrationTest.testRemove() {
        br.unicamp.mc536.t2010s2a.forum.domain.RedeTrabalho obj = dod.getRandomRedeTrabalho();
        org.junit.Assert.assertNotNull("Data on demand for 'RedeTrabalho' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'RedeTrabalho' failed to provide an identifier", id);
        obj = br.unicamp.mc536.t2010s2a.forum.domain.RedeTrabalho.findRedeTrabalho(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'RedeTrabalho' with identifier '" + id + "'", br.unicamp.mc536.t2010s2a.forum.domain.RedeTrabalho.findRedeTrabalho(id));
    }
    
}
