// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.unicamp.mc536.t2010s2a.forum.domain;

import br.unicamp.mc536.t2010s2a.forum.domain.RedeTrabalhoUsuarioDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect RedeTrabalhoUsuarioIntegrationTest_Roo_IntegrationTest {
    
    declare @type: RedeTrabalhoUsuarioIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: RedeTrabalhoUsuarioIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    @Autowired
    private RedeTrabalhoUsuarioDataOnDemand RedeTrabalhoUsuarioIntegrationTest.dod;
    
    @Test
    public void RedeTrabalhoUsuarioIntegrationTest.testCountRedeTrabalhoUsuarios() {
        org.junit.Assert.assertNotNull("Data on demand for 'RedeTrabalhoUsuario' failed to initialize correctly", dod.getRandomRedeTrabalhoUsuario());
        long count = br.unicamp.mc536.t2010s2a.forum.domain.RedeTrabalhoUsuario.countRedeTrabalhoUsuarios();
        org.junit.Assert.assertTrue("Counter for 'RedeTrabalhoUsuario' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void RedeTrabalhoUsuarioIntegrationTest.testFindRedeTrabalhoUsuario() {
        br.unicamp.mc536.t2010s2a.forum.domain.RedeTrabalhoUsuario obj = dod.getRandomRedeTrabalhoUsuario();
        org.junit.Assert.assertNotNull("Data on demand for 'RedeTrabalhoUsuario' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'RedeTrabalhoUsuario' failed to provide an identifier", id);
        obj = br.unicamp.mc536.t2010s2a.forum.domain.RedeTrabalhoUsuario.findRedeTrabalhoUsuario(id);
        org.junit.Assert.assertNotNull("Find method for 'RedeTrabalhoUsuario' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'RedeTrabalhoUsuario' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void RedeTrabalhoUsuarioIntegrationTest.testFindAllRedeTrabalhoUsuarios() {
        org.junit.Assert.assertNotNull("Data on demand for 'RedeTrabalhoUsuario' failed to initialize correctly", dod.getRandomRedeTrabalhoUsuario());
        long count = br.unicamp.mc536.t2010s2a.forum.domain.RedeTrabalhoUsuario.countRedeTrabalhoUsuarios();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'RedeTrabalhoUsuario', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<br.unicamp.mc536.t2010s2a.forum.domain.RedeTrabalhoUsuario> result = br.unicamp.mc536.t2010s2a.forum.domain.RedeTrabalhoUsuario.findAllRedeTrabalhoUsuarios();
        org.junit.Assert.assertNotNull("Find all method for 'RedeTrabalhoUsuario' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'RedeTrabalhoUsuario' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void RedeTrabalhoUsuarioIntegrationTest.testFindRedeTrabalhoUsuarioEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'RedeTrabalhoUsuario' failed to initialize correctly", dod.getRandomRedeTrabalhoUsuario());
        long count = br.unicamp.mc536.t2010s2a.forum.domain.RedeTrabalhoUsuario.countRedeTrabalhoUsuarios();
        if (count > 20) count = 20;
        java.util.List<br.unicamp.mc536.t2010s2a.forum.domain.RedeTrabalhoUsuario> result = br.unicamp.mc536.t2010s2a.forum.domain.RedeTrabalhoUsuario.findRedeTrabalhoUsuarioEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'RedeTrabalhoUsuario' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'RedeTrabalhoUsuario' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    @Transactional
    public void RedeTrabalhoUsuarioIntegrationTest.testFlush() {
        br.unicamp.mc536.t2010s2a.forum.domain.RedeTrabalhoUsuario obj = dod.getRandomRedeTrabalhoUsuario();
        org.junit.Assert.assertNotNull("Data on demand for 'RedeTrabalhoUsuario' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'RedeTrabalhoUsuario' failed to provide an identifier", id);
        obj = br.unicamp.mc536.t2010s2a.forum.domain.RedeTrabalhoUsuario.findRedeTrabalhoUsuario(id);
        org.junit.Assert.assertNotNull("Find method for 'RedeTrabalhoUsuario' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyRedeTrabalhoUsuario(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'RedeTrabalhoUsuario' failed to increment on flush directive", obj.getVersion() > currentVersion || !modified);
    }
    
    @Test
    @Transactional
    public void RedeTrabalhoUsuarioIntegrationTest.testMerge() {
        br.unicamp.mc536.t2010s2a.forum.domain.RedeTrabalhoUsuario obj = dod.getRandomRedeTrabalhoUsuario();
        org.junit.Assert.assertNotNull("Data on demand for 'RedeTrabalhoUsuario' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'RedeTrabalhoUsuario' failed to provide an identifier", id);
        obj = br.unicamp.mc536.t2010s2a.forum.domain.RedeTrabalhoUsuario.findRedeTrabalhoUsuario(id);
        boolean modified =  dod.modifyRedeTrabalhoUsuario(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.merge();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'RedeTrabalhoUsuario' failed to increment on merge and flush directive", obj.getVersion() > currentVersion || !modified);
    }
    
    @Test
    @Transactional
    public void RedeTrabalhoUsuarioIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'RedeTrabalhoUsuario' failed to initialize correctly", dod.getRandomRedeTrabalhoUsuario());
        br.unicamp.mc536.t2010s2a.forum.domain.RedeTrabalhoUsuario obj = dod.getNewTransientRedeTrabalhoUsuario(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'RedeTrabalhoUsuario' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'RedeTrabalhoUsuario' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'RedeTrabalhoUsuario' identifier to no longer be null", obj.getId());
    }
    
    @Test
    @Transactional
    public void RedeTrabalhoUsuarioIntegrationTest.testRemove() {
        br.unicamp.mc536.t2010s2a.forum.domain.RedeTrabalhoUsuario obj = dod.getRandomRedeTrabalhoUsuario();
        org.junit.Assert.assertNotNull("Data on demand for 'RedeTrabalhoUsuario' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'RedeTrabalhoUsuario' failed to provide an identifier", id);
        obj = br.unicamp.mc536.t2010s2a.forum.domain.RedeTrabalhoUsuario.findRedeTrabalhoUsuario(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'RedeTrabalhoUsuario' with identifier '" + id + "'", br.unicamp.mc536.t2010s2a.forum.domain.RedeTrabalhoUsuario.findRedeTrabalhoUsuario(id));
    }
    
}
