// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.unicamp.mc536.t2010s2a.forum.domain;

import br.unicamp.mc536.t2010s2a.forum.domain.UsuarioDocumentoDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect UsuarioDocumentoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: UsuarioDocumentoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: UsuarioDocumentoIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    @Autowired
    private UsuarioDocumentoDataOnDemand UsuarioDocumentoIntegrationTest.dod;
    
    @Test
    public void UsuarioDocumentoIntegrationTest.testCountUsuarioDocumentoes() {
        org.junit.Assert.assertNotNull("Data on demand for 'UsuarioDocumento' failed to initialize correctly", dod.getRandomUsuarioDocumento());
        long count = br.unicamp.mc536.t2010s2a.forum.domain.UsuarioDocumento.countUsuarioDocumentoes();
        org.junit.Assert.assertTrue("Counter for 'UsuarioDocumento' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void UsuarioDocumentoIntegrationTest.testFindUsuarioDocumento() {
        br.unicamp.mc536.t2010s2a.forum.domain.UsuarioDocumento obj = dod.getRandomUsuarioDocumento();
        org.junit.Assert.assertNotNull("Data on demand for 'UsuarioDocumento' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'UsuarioDocumento' failed to provide an identifier", id);
        obj = br.unicamp.mc536.t2010s2a.forum.domain.UsuarioDocumento.findUsuarioDocumento(id);
        org.junit.Assert.assertNotNull("Find method for 'UsuarioDocumento' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'UsuarioDocumento' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void UsuarioDocumentoIntegrationTest.testFindAllUsuarioDocumentoes() {
        org.junit.Assert.assertNotNull("Data on demand for 'UsuarioDocumento' failed to initialize correctly", dod.getRandomUsuarioDocumento());
        long count = br.unicamp.mc536.t2010s2a.forum.domain.UsuarioDocumento.countUsuarioDocumentoes();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'UsuarioDocumento', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<br.unicamp.mc536.t2010s2a.forum.domain.UsuarioDocumento> result = br.unicamp.mc536.t2010s2a.forum.domain.UsuarioDocumento.findAllUsuarioDocumentoes();
        org.junit.Assert.assertNotNull("Find all method for 'UsuarioDocumento' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'UsuarioDocumento' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void UsuarioDocumentoIntegrationTest.testFindUsuarioDocumentoEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'UsuarioDocumento' failed to initialize correctly", dod.getRandomUsuarioDocumento());
        long count = br.unicamp.mc536.t2010s2a.forum.domain.UsuarioDocumento.countUsuarioDocumentoes();
        if (count > 20) count = 20;
        java.util.List<br.unicamp.mc536.t2010s2a.forum.domain.UsuarioDocumento> result = br.unicamp.mc536.t2010s2a.forum.domain.UsuarioDocumento.findUsuarioDocumentoEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'UsuarioDocumento' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'UsuarioDocumento' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    @Transactional
    public void UsuarioDocumentoIntegrationTest.testFlush() {
        br.unicamp.mc536.t2010s2a.forum.domain.UsuarioDocumento obj = dod.getRandomUsuarioDocumento();
        org.junit.Assert.assertNotNull("Data on demand for 'UsuarioDocumento' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'UsuarioDocumento' failed to provide an identifier", id);
        obj = br.unicamp.mc536.t2010s2a.forum.domain.UsuarioDocumento.findUsuarioDocumento(id);
        org.junit.Assert.assertNotNull("Find method for 'UsuarioDocumento' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyUsuarioDocumento(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'UsuarioDocumento' failed to increment on flush directive", obj.getVersion() > currentVersion || !modified);
    }
    
    @Test
    @Transactional
    public void UsuarioDocumentoIntegrationTest.testMerge() {
        br.unicamp.mc536.t2010s2a.forum.domain.UsuarioDocumento obj = dod.getRandomUsuarioDocumento();
        org.junit.Assert.assertNotNull("Data on demand for 'UsuarioDocumento' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'UsuarioDocumento' failed to provide an identifier", id);
        obj = br.unicamp.mc536.t2010s2a.forum.domain.UsuarioDocumento.findUsuarioDocumento(id);
        boolean modified =  dod.modifyUsuarioDocumento(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.merge();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'UsuarioDocumento' failed to increment on merge and flush directive", obj.getVersion() > currentVersion || !modified);
    }
    
    @Test
    @Transactional
    public void UsuarioDocumentoIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'UsuarioDocumento' failed to initialize correctly", dod.getRandomUsuarioDocumento());
        br.unicamp.mc536.t2010s2a.forum.domain.UsuarioDocumento obj = dod.getNewTransientUsuarioDocumento(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'UsuarioDocumento' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'UsuarioDocumento' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'UsuarioDocumento' identifier to no longer be null", obj.getId());
    }
    
    @Test
    @Transactional
    public void UsuarioDocumentoIntegrationTest.testRemove() {
        br.unicamp.mc536.t2010s2a.forum.domain.UsuarioDocumento obj = dod.getRandomUsuarioDocumento();
        org.junit.Assert.assertNotNull("Data on demand for 'UsuarioDocumento' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'UsuarioDocumento' failed to provide an identifier", id);
        obj = br.unicamp.mc536.t2010s2a.forum.domain.UsuarioDocumento.findUsuarioDocumento(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'UsuarioDocumento' with identifier '" + id + "'", br.unicamp.mc536.t2010s2a.forum.domain.UsuarioDocumento.findUsuarioDocumento(id));
    }
    
}
