// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.unicamp.mc536.t2010s2a.forum.domain;

import br.unicamp.mc536.t2010s2a.forum.domain.IdiomaDataOnDemand;
import br.unicamp.mc536.t2010s2a.forum.domain.UsuarioDataOnDemand;
import br.unicamp.mc536.t2010s2a.forum.domain.UsuarioIdioma;
import java.util.List;
import java.util.Random;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

privileged aspect UsuarioIdiomaDataOnDemand_Roo_DataOnDemand {
    
    declare @type: UsuarioIdiomaDataOnDemand: @Component;
    
    private Random UsuarioIdiomaDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<UsuarioIdioma> UsuarioIdiomaDataOnDemand.data;
    
    @Autowired
    private IdiomaDataOnDemand UsuarioIdiomaDataOnDemand.idiomaDataOnDemand;
    
    @Autowired
    private UsuarioDataOnDemand UsuarioIdiomaDataOnDemand.usuarioDataOnDemand;
    
    public UsuarioIdioma UsuarioIdiomaDataOnDemand.getNewTransientUsuarioIdioma(int index) {
        br.unicamp.mc536.t2010s2a.forum.domain.UsuarioIdioma obj = new br.unicamp.mc536.t2010s2a.forum.domain.UsuarioIdioma();
        obj.setIdIdioma(idiomaDataOnDemand.getRandomIdioma());
        obj.setIdUsuario(usuarioDataOnDemand.getRandomUsuario());
        return obj;
    }
    
    public UsuarioIdioma UsuarioIdiomaDataOnDemand.getSpecificUsuarioIdioma(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        UsuarioIdioma obj = data.get(index);
        return UsuarioIdioma.findUsuarioIdioma(obj.getId());
    }
    
    public UsuarioIdioma UsuarioIdiomaDataOnDemand.getRandomUsuarioIdioma() {
        init();
        UsuarioIdioma obj = data.get(rnd.nextInt(data.size()));
        return UsuarioIdioma.findUsuarioIdioma(obj.getId());
    }
    
    public boolean UsuarioIdiomaDataOnDemand.modifyUsuarioIdioma(UsuarioIdioma obj) {
        return false;
    }
    
    @Transactional(propagation = Propagation.REQUIRES_NEW)
    public void UsuarioIdiomaDataOnDemand.init() {
        if (data != null && !data.isEmpty()) {
            return;
        }
        
        data = br.unicamp.mc536.t2010s2a.forum.domain.UsuarioIdioma.findUsuarioIdiomaEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'UsuarioIdioma' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<br.unicamp.mc536.t2010s2a.forum.domain.UsuarioIdioma>();
        for (int i = 0; i < 10; i++) {
            br.unicamp.mc536.t2010s2a.forum.domain.UsuarioIdioma obj = getNewTransientUsuarioIdioma(i);
            obj.persist();
            data.add(obj);
        }
    }
    
}
