// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.unicamp.mc536.t2010s2a.forum.domain;

import br.unicamp.mc536.t2010s2a.forum.domain.ComentarioDocumento;
import br.unicamp.mc536.t2010s2a.forum.domain.DocumentoDataOnDemand;
import java.util.List;
import java.util.Random;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ComentarioDocumentoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ComentarioDocumentoDataOnDemand: @Component;
    
    private Random ComentarioDocumentoDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<ComentarioDocumento> ComentarioDocumentoDataOnDemand.data;
    
    @Autowired
    private DocumentoDataOnDemand ComentarioDocumentoDataOnDemand.documentoDataOnDemand;
    
    public ComentarioDocumento ComentarioDocumentoDataOnDemand.getNewTransientComentarioDocumento(int index) {
        br.unicamp.mc536.t2010s2a.forum.domain.ComentarioDocumento obj = new br.unicamp.mc536.t2010s2a.forum.domain.ComentarioDocumento();
        obj.setDsComentario("dsComentario_" + index);
        obj.setDtInclusao(new java.util.Date());
        obj.setIdComentario(null);
        obj.setIdDocumento(documentoDataOnDemand.getRandomDocumento());
        obj.setIdUsuario(null);
        obj.setTpReferenciaDocumento(br.unicamp.mc536.t2010s2a.forum.reference.ReferenciaDocumento.class.getEnumConstants()[0]);
        return obj;
    }
    
    public ComentarioDocumento ComentarioDocumentoDataOnDemand.getSpecificComentarioDocumento(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        ComentarioDocumento obj = data.get(index);
        return ComentarioDocumento.findComentarioDocumento(obj.getId());
    }
    
    public ComentarioDocumento ComentarioDocumentoDataOnDemand.getRandomComentarioDocumento() {
        init();
        ComentarioDocumento obj = data.get(rnd.nextInt(data.size()));
        return ComentarioDocumento.findComentarioDocumento(obj.getId());
    }
    
    public boolean ComentarioDocumentoDataOnDemand.modifyComentarioDocumento(ComentarioDocumento obj) {
        return false;
    }
    
    @Transactional(propagation = Propagation.REQUIRES_NEW)
    public void ComentarioDocumentoDataOnDemand.init() {
        if (data != null && !data.isEmpty()) {
            return;
        }
        
        data = br.unicamp.mc536.t2010s2a.forum.domain.ComentarioDocumento.findComentarioDocumentoEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'ComentarioDocumento' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<br.unicamp.mc536.t2010s2a.forum.domain.ComentarioDocumento>();
        for (int i = 0; i < 10; i++) {
            br.unicamp.mc536.t2010s2a.forum.domain.ComentarioDocumento obj = getNewTransientComentarioDocumento(i);
            obj.persist();
            data.add(obj);
        }
    }
    
}
