// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.unicamp.mc536.t2010s2a.forum.domain;

import br.unicamp.mc536.t2010s2a.forum.domain.DocumentoDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DocumentoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: DocumentoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: DocumentoIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    @Autowired
    private DocumentoDataOnDemand DocumentoIntegrationTest.dod;
    
    @Test
    public void DocumentoIntegrationTest.testCountDocumentoes() {
        org.junit.Assert.assertNotNull("Data on demand for 'Documento' failed to initialize correctly", dod.getRandomDocumento());
        long count = br.unicamp.mc536.t2010s2a.forum.domain.Documento.countDocumentoes();
        org.junit.Assert.assertTrue("Counter for 'Documento' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void DocumentoIntegrationTest.testFindDocumento() {
        br.unicamp.mc536.t2010s2a.forum.domain.Documento obj = dod.getRandomDocumento();
        org.junit.Assert.assertNotNull("Data on demand for 'Documento' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Documento' failed to provide an identifier", id);
        obj = br.unicamp.mc536.t2010s2a.forum.domain.Documento.findDocumento(id);
        org.junit.Assert.assertNotNull("Find method for 'Documento' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Documento' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void DocumentoIntegrationTest.testFindAllDocumentoes() {
        org.junit.Assert.assertNotNull("Data on demand for 'Documento' failed to initialize correctly", dod.getRandomDocumento());
        long count = br.unicamp.mc536.t2010s2a.forum.domain.Documento.countDocumentoes();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Documento', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<br.unicamp.mc536.t2010s2a.forum.domain.Documento> result = br.unicamp.mc536.t2010s2a.forum.domain.Documento.findAllDocumentoes();
        org.junit.Assert.assertNotNull("Find all method for 'Documento' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Documento' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void DocumentoIntegrationTest.testFindDocumentoEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Documento' failed to initialize correctly", dod.getRandomDocumento());
        long count = br.unicamp.mc536.t2010s2a.forum.domain.Documento.countDocumentoes();
        if (count > 20) count = 20;
        java.util.List<br.unicamp.mc536.t2010s2a.forum.domain.Documento> result = br.unicamp.mc536.t2010s2a.forum.domain.Documento.findDocumentoEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Documento' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Documento' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    @Transactional
    public void DocumentoIntegrationTest.testFlush() {
        br.unicamp.mc536.t2010s2a.forum.domain.Documento obj = dod.getRandomDocumento();
        org.junit.Assert.assertNotNull("Data on demand for 'Documento' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Documento' failed to provide an identifier", id);
        obj = br.unicamp.mc536.t2010s2a.forum.domain.Documento.findDocumento(id);
        org.junit.Assert.assertNotNull("Find method for 'Documento' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyDocumento(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Documento' failed to increment on flush directive", obj.getVersion() > currentVersion || !modified);
    }
    
    @Test
    @Transactional
    public void DocumentoIntegrationTest.testMerge() {
        br.unicamp.mc536.t2010s2a.forum.domain.Documento obj = dod.getRandomDocumento();
        org.junit.Assert.assertNotNull("Data on demand for 'Documento' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Documento' failed to provide an identifier", id);
        obj = br.unicamp.mc536.t2010s2a.forum.domain.Documento.findDocumento(id);
        boolean modified =  dod.modifyDocumento(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.merge();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Documento' failed to increment on merge and flush directive", obj.getVersion() > currentVersion || !modified);
    }
    
    @Test
    @Transactional
    public void DocumentoIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Documento' failed to initialize correctly", dod.getRandomDocumento());
        br.unicamp.mc536.t2010s2a.forum.domain.Documento obj = dod.getNewTransientDocumento(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Documento' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Documento' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Documento' identifier to no longer be null", obj.getId());
    }
    
    @Test
    @Transactional
    public void DocumentoIntegrationTest.testRemove() {
        br.unicamp.mc536.t2010s2a.forum.domain.Documento obj = dod.getRandomDocumento();
        org.junit.Assert.assertNotNull("Data on demand for 'Documento' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Documento' failed to provide an identifier", id);
        obj = br.unicamp.mc536.t2010s2a.forum.domain.Documento.findDocumento(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Documento' with identifier '" + id + "'", br.unicamp.mc536.t2010s2a.forum.domain.Documento.findDocumento(id));
    }
    
}
