// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.unicamp.mc536.t2010s2a.forum.domain;

import br.unicamp.mc536.t2010s2a.forum.domain.Idioma;
import br.unicamp.mc536.t2010s2a.forum.domain.PaisDataOnDemand;
import java.util.List;
import java.util.Random;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

privileged aspect IdiomaDataOnDemand_Roo_DataOnDemand {
    
    declare @type: IdiomaDataOnDemand: @Component;
    
    private Random IdiomaDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Idioma> IdiomaDataOnDemand.data;
    
    @Autowired
    private PaisDataOnDemand IdiomaDataOnDemand.paisDataOnDemand;
    
    public Idioma IdiomaDataOnDemand.getNewTransientIdioma(int index) {
        br.unicamp.mc536.t2010s2a.forum.domain.Idioma obj = new br.unicamp.mc536.t2010s2a.forum.domain.Idioma();
        obj.setDsDetalhadaIdioma("dsDetalhadaIdioma_" + index);
        java.lang.String dsIdioma = "dsIdioma_" + index;
        if (dsIdioma.length() > 255) {
            dsIdioma  = dsIdioma.substring(0, 255);
        }
        obj.setDsIdioma(dsIdioma);
        obj.setIdPais(paisDataOnDemand.getRandomPais());
        java.lang.String nmIdioma = "nmIdioma_" + index;
        if (nmIdioma.length() > 50) {
            nmIdioma  = nmIdioma.substring(0, 50);
        }
        obj.setNmIdioma(nmIdioma);
        obj.setNmRegiao("nmRegiao_" + index);
        java.lang.String sgIdioma = "sg_" + index;
        if (sgIdioma.length() > 4) {
            sgIdioma  = sgIdioma.substring(0, 4);
        }
        obj.setSgIdioma(sgIdioma);
        return obj;
    }
    
    public Idioma IdiomaDataOnDemand.getSpecificIdioma(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Idioma obj = data.get(index);
        return Idioma.findIdioma(obj.getId());
    }
    
    public Idioma IdiomaDataOnDemand.getRandomIdioma() {
        init();
        Idioma obj = data.get(rnd.nextInt(data.size()));
        return Idioma.findIdioma(obj.getId());
    }
    
    public boolean IdiomaDataOnDemand.modifyIdioma(Idioma obj) {
        return false;
    }
    
    @Transactional(propagation = Propagation.REQUIRES_NEW)
    public void IdiomaDataOnDemand.init() {
        if (data != null && !data.isEmpty()) {
            return;
        }
        
        data = br.unicamp.mc536.t2010s2a.forum.domain.Idioma.findIdiomaEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Idioma' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<br.unicamp.mc536.t2010s2a.forum.domain.Idioma>();
        for (int i = 0; i < 10; i++) {
            br.unicamp.mc536.t2010s2a.forum.domain.Idioma obj = getNewTransientIdioma(i);
            obj.persist();
            data.add(obj);
        }
    }
    
}
