// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.unicamp.mc536.t2010s2a.forum.domain;

import br.unicamp.mc536.t2010s2a.forum.domain.Pais;
import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PaisDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PaisDataOnDemand: @Component;
    
    private Random PaisDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Pais> PaisDataOnDemand.data;
    
    public Pais PaisDataOnDemand.getNewTransientPais(int index) {
        br.unicamp.mc536.t2010s2a.forum.domain.Pais obj = new br.unicamp.mc536.t2010s2a.forum.domain.Pais();
        obj.setDsPais("dsPais_" + index);
        java.lang.String nmPais = "nmPais_" + index;
        if (nmPais.length() > 50) {
            nmPais  = nmPais.substring(0, 50);
        }
        obj.setNmPais(nmPais);
        return obj;
    }
    
    public Pais PaisDataOnDemand.getSpecificPais(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Pais obj = data.get(index);
        return Pais.findPais(obj.getId());
    }
    
    public Pais PaisDataOnDemand.getRandomPais() {
        init();
        Pais obj = data.get(rnd.nextInt(data.size()));
        return Pais.findPais(obj.getId());
    }
    
    public boolean PaisDataOnDemand.modifyPais(Pais obj) {
        return false;
    }
    
    @Transactional(propagation = Propagation.REQUIRES_NEW)
    public void PaisDataOnDemand.init() {
        if (data != null && !data.isEmpty()) {
            return;
        }
        
        data = br.unicamp.mc536.t2010s2a.forum.domain.Pais.findPaisEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Pais' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<br.unicamp.mc536.t2010s2a.forum.domain.Pais>();
        for (int i = 0; i < 10; i++) {
            br.unicamp.mc536.t2010s2a.forum.domain.Pais obj = getNewTransientPais(i);
            obj.persist();
            data.add(obj);
        }
    }
    
}
