// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.unicamp.mc536.t2010s2a.forum.domain;

import br.unicamp.mc536.t2010s2a.forum.domain.DocumentoDataOnDemand;
import br.unicamp.mc536.t2010s2a.forum.domain.IdiomaDataOnDemand;
import br.unicamp.mc536.t2010s2a.forum.domain.PalavraDocumento;
import java.util.List;
import java.util.Random;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PalavraDocumentoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PalavraDocumentoDataOnDemand: @Component;
    
    private Random PalavraDocumentoDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<PalavraDocumento> PalavraDocumentoDataOnDemand.data;
    
    @Autowired
    private DocumentoDataOnDemand PalavraDocumentoDataOnDemand.documentoDataOnDemand;
    
    @Autowired
    private IdiomaDataOnDemand PalavraDocumentoDataOnDemand.idiomaDataOnDemand;
    
    public PalavraDocumento PalavraDocumentoDataOnDemand.getNewTransientPalavraDocumento(int index) {
        br.unicamp.mc536.t2010s2a.forum.domain.PalavraDocumento obj = new br.unicamp.mc536.t2010s2a.forum.domain.PalavraDocumento();
        java.lang.String dsPalavrasChaves = "dsPalavrasChaves_" + index;
        if (dsPalavrasChaves.length() > 200) {
            dsPalavrasChaves  = dsPalavrasChaves.substring(0, 200);
        }
        obj.setDsPalavrasChaves(dsPalavrasChaves);
        obj.setIdDocumento(documentoDataOnDemand.getRandomDocumento());
        obj.setIdIdioma(idiomaDataOnDemand.getRandomIdioma());
        return obj;
    }
    
    public PalavraDocumento PalavraDocumentoDataOnDemand.getSpecificPalavraDocumento(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        PalavraDocumento obj = data.get(index);
        return PalavraDocumento.findPalavraDocumento(obj.getId());
    }
    
    public PalavraDocumento PalavraDocumentoDataOnDemand.getRandomPalavraDocumento() {
        init();
        PalavraDocumento obj = data.get(rnd.nextInt(data.size()));
        return PalavraDocumento.findPalavraDocumento(obj.getId());
    }
    
    public boolean PalavraDocumentoDataOnDemand.modifyPalavraDocumento(PalavraDocumento obj) {
        return false;
    }
    
    @Transactional(propagation = Propagation.REQUIRES_NEW)
    public void PalavraDocumentoDataOnDemand.init() {
        if (data != null && !data.isEmpty()) {
            return;
        }
        
        data = br.unicamp.mc536.t2010s2a.forum.domain.PalavraDocumento.findPalavraDocumentoEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'PalavraDocumento' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<br.unicamp.mc536.t2010s2a.forum.domain.PalavraDocumento>();
        for (int i = 0; i < 10; i++) {
            br.unicamp.mc536.t2010s2a.forum.domain.PalavraDocumento obj = getNewTransientPalavraDocumento(i);
            obj.persist();
            data.add(obj);
        }
    }
    
}
