// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.unicamp.mc536.t2010s2a.forum.domain;

import br.unicamp.mc536.t2010s2a.forum.domain.Programa;
import br.unicamp.mc536.t2010s2a.forum.domain.UsuarioDataOnDemand;
import java.util.List;
import java.util.Random;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ProgramaDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ProgramaDataOnDemand: @Component;
    
    private Random ProgramaDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Programa> ProgramaDataOnDemand.data;
    
    @Autowired
    private UsuarioDataOnDemand ProgramaDataOnDemand.usuarioDataOnDemand;
    
    public Programa ProgramaDataOnDemand.getNewTransientPrograma(int index) {
        br.unicamp.mc536.t2010s2a.forum.domain.Programa obj = new br.unicamp.mc536.t2010s2a.forum.domain.Programa();
        obj.setDsDetalhadaPrograma("dsDetalhadaPrograma_" + index);
        java.lang.String dsPrograma = "dsPrograma_" + index;
        if (dsPrograma.length() > 255) {
            dsPrograma  = dsPrograma.substring(0, 255);
        }
        obj.setDsPrograma(dsPrograma);
        obj.setIdUsuario(usuarioDataOnDemand.getRandomUsuario());
        java.lang.String nmPrograma = "nmPrograma_" + index;
        if (nmPrograma.length() > 255) {
            nmPrograma  = nmPrograma.substring(0, 255);
        }
        obj.setNmPrograma(nmPrograma);
        return obj;
    }
    
    public Programa ProgramaDataOnDemand.getSpecificPrograma(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Programa obj = data.get(index);
        return Programa.findPrograma(obj.getId());
    }
    
    public Programa ProgramaDataOnDemand.getRandomPrograma() {
        init();
        Programa obj = data.get(rnd.nextInt(data.size()));
        return Programa.findPrograma(obj.getId());
    }
    
    public boolean ProgramaDataOnDemand.modifyPrograma(Programa obj) {
        return false;
    }
    
    @Transactional(propagation = Propagation.REQUIRES_NEW)
    public void ProgramaDataOnDemand.init() {
        if (data != null && !data.isEmpty()) {
            return;
        }
        
        data = br.unicamp.mc536.t2010s2a.forum.domain.Programa.findProgramaEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Programa' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<br.unicamp.mc536.t2010s2a.forum.domain.Programa>();
        for (int i = 0; i < 10; i++) {
            br.unicamp.mc536.t2010s2a.forum.domain.Programa obj = getNewTransientPrograma(i);
            obj.persist();
            data.add(obj);
        }
    }
    
}
