// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.unicamp.mc536.t2010s2a.forum.domain;

import br.unicamp.mc536.t2010s2a.forum.domain.DocumentoDataOnDemand;
import br.unicamp.mc536.t2010s2a.forum.domain.UsuarioDataOnDemand;
import br.unicamp.mc536.t2010s2a.forum.domain.UsuarioDocumento;
import java.util.List;
import java.util.Random;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

privileged aspect UsuarioDocumentoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: UsuarioDocumentoDataOnDemand: @Component;
    
    private Random UsuarioDocumentoDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<UsuarioDocumento> UsuarioDocumentoDataOnDemand.data;
    
    @Autowired
    private DocumentoDataOnDemand UsuarioDocumentoDataOnDemand.documentoDataOnDemand;
    
    @Autowired
    private UsuarioDataOnDemand UsuarioDocumentoDataOnDemand.usuarioDataOnDemand;
    
    public UsuarioDocumento UsuarioDocumentoDataOnDemand.getNewTransientUsuarioDocumento(int index) {
        br.unicamp.mc536.t2010s2a.forum.domain.UsuarioDocumento obj = new br.unicamp.mc536.t2010s2a.forum.domain.UsuarioDocumento();
        obj.setDtInclusao(new java.util.Date());
        obj.setIdDocumento(documentoDataOnDemand.getRandomDocumento());
        obj.setIdUsuario(usuarioDataOnDemand.getRandomUsuario());
        return obj;
    }
    
    public UsuarioDocumento UsuarioDocumentoDataOnDemand.getSpecificUsuarioDocumento(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        UsuarioDocumento obj = data.get(index);
        return UsuarioDocumento.findUsuarioDocumento(obj.getId());
    }
    
    public UsuarioDocumento UsuarioDocumentoDataOnDemand.getRandomUsuarioDocumento() {
        init();
        UsuarioDocumento obj = data.get(rnd.nextInt(data.size()));
        return UsuarioDocumento.findUsuarioDocumento(obj.getId());
    }
    
    public boolean UsuarioDocumentoDataOnDemand.modifyUsuarioDocumento(UsuarioDocumento obj) {
        return false;
    }
    
    @Transactional(propagation = Propagation.REQUIRES_NEW)
    public void UsuarioDocumentoDataOnDemand.init() {
        if (data != null && !data.isEmpty()) {
            return;
        }
        
        data = br.unicamp.mc536.t2010s2a.forum.domain.UsuarioDocumento.findUsuarioDocumentoEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'UsuarioDocumento' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<br.unicamp.mc536.t2010s2a.forum.domain.UsuarioDocumento>();
        for (int i = 0; i < 10; i++) {
            br.unicamp.mc536.t2010s2a.forum.domain.UsuarioDocumento obj = getNewTransientUsuarioDocumento(i);
            obj.persist();
            data.add(obj);
        }
    }
    
}
