// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.unicamp.mc536.t2010s2a.forum.domain;

import br.unicamp.mc536.t2010s2a.forum.domain.IdiomaDataOnDemand;
import br.unicamp.mc536.t2010s2a.forum.domain.Usuario;
import java.util.List;
import java.util.Random;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

privileged aspect UsuarioDataOnDemand_Roo_DataOnDemand {
    
    declare @type: UsuarioDataOnDemand: @Component;
    
    private Random UsuarioDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Usuario> UsuarioDataOnDemand.data;
    
    @Autowired
    private IdiomaDataOnDemand UsuarioDataOnDemand.idiomaDataOnDemand;
    
    public Usuario UsuarioDataOnDemand.getNewTransientUsuario(int index) {
        br.unicamp.mc536.t2010s2a.forum.domain.Usuario obj = new br.unicamp.mc536.t2010s2a.forum.domain.Usuario();
        obj.setDsInstituicao("dsInstituicao_" + index);
        java.lang.String dsLogin = "dsLogin_" + index;
        if (dsLogin.length() > 10) {
            dsLogin  = dsLogin.substring(0, 10);
        }
        obj.setDsLogin(dsLogin);
        java.lang.String dsSenha = "dsSenha_" + index;
        if (dsSenha.length() > 10) {
            dsSenha  = dsSenha.substring(0, 10);
        }
        obj.setDsSenha(dsSenha);
        obj.setDtInclusao(new java.util.Date());
        java.lang.String email = "email_" + index;
        if (email.length() > 255) {
            email  = email.substring(0, 255);
        }
        obj.setEmail(email);
        obj.setFlAtivo(true);
        obj.setFlInstitucional(true);
        obj.setIdIdiomaNativo(idiomaDataOnDemand.getRandomIdioma());
        obj.setNmInstituicao("nmInstituicao_" + index);
        java.lang.String nmUsuario = "nmUsuario_" + index;
        if (nmUsuario.length() > 255) {
            nmUsuario  = nmUsuario.substring(0, 255);
        }
        obj.setNmUsuario(nmUsuario);
        obj.setTpUsuario(br.unicamp.mc536.t2010s2a.forum.reference.UsuarioType.class.getEnumConstants()[0]);
        return obj;
    }
    
    public Usuario UsuarioDataOnDemand.getSpecificUsuario(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Usuario obj = data.get(index);
        return Usuario.findUsuario(obj.getId());
    }
    
    public Usuario UsuarioDataOnDemand.getRandomUsuario() {
        init();
        Usuario obj = data.get(rnd.nextInt(data.size()));
        return Usuario.findUsuario(obj.getId());
    }
    
    public boolean UsuarioDataOnDemand.modifyUsuario(Usuario obj) {
        return false;
    }
    
    @Transactional(propagation = Propagation.REQUIRES_NEW)
    public void UsuarioDataOnDemand.init() {
        if (data != null && !data.isEmpty()) {
            return;
        }
        
        data = br.unicamp.mc536.t2010s2a.forum.domain.Usuario.findUsuarioEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Usuario' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<br.unicamp.mc536.t2010s2a.forum.domain.Usuario>();
        for (int i = 0; i < 10; i++) {
            br.unicamp.mc536.t2010s2a.forum.domain.Usuario obj = getNewTransientUsuario(i);
            obj.persist();
            data.add(obj);
        }
    }
    
}
