// Constantes para operacoes entre o servidor e o cliente mini-amazon
#define OBTER_TODOS_ISBNS "OBTER_TODOS_ISBNS"
#define OBTER_DESCRICAO_POR_ISBN "OBTER_DESCRICAO_POR_ISBN"
#define OBTER_LIVRO_POR_ISBN "OBTER_LIVRO_POR_ISBN"
#define OBTER_TODOS_LIVROS "OBTER_TODOS_LIVROS"
#define ALTERAR_NR_EXEMPLARES_ESTOQUE "ALTERAR_NR_EXEMPLARES_ESTOQUE"
#define OBTER_NR_EXEMPLARES_ESTOQUE "OBTER_NR_EXEMPLARES_ESTOQUE"

#define RESPONSE_END "RESPONSE_END"
#define RESPONSE_USUARIO_INVALIDO = "RESPONSE_USUARIO_INVALIDO"
#define RESPONSE_USUARIO_SEM_PERMISSAO = "RESPONSE_USUARIO_SEM_PERMISSAO"